### ISSUE TITLE
JsoDecodeError

### ISSUE THREAD

**Issue by AsadBukharee** [duyixian1234/fastapi-redis-session#3]
INFO:     127.0.0.1:50564 - "POST /setSession HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Asad\PycharmProjects\FAST_API\email_engine\.\app.py", line 112, in _setSession
    sessionData = await request.json()
  File "C:\Users\Asad\PycharmProjects\FAST_API\attech-identityprovider\venv\lib\site-packages\starlette\requests.py", line 235, in json
    self._json = json.loads(body)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AsadBukharee** [comment]
@duyixian1234 please help me to find issue. I just executed the given example.

**Comment by duyixian1234** [comment]
What's your request body when post to "/setSession", It seems that the data your post is not a valid json.
Maybe you can try again with the example data below。
```bash
curl -H "Content-Type: application/json" -X POST -d "{\"abc\":123}" "http://localhost:($PORT)/setSession"
```

**Comment by AsadBukharee** [comment]
yes you are right, it was not a valid json
